### ISSUE TITLE
Add K8s deployment

### ISSUE THREAD

**Issue by MrF3lix** [Agile-Waterfall-Inc/flooq#10]

**Comment by riesentoaster** [comment]
Links:
- https://info.cloudlab.zhaw.ch/pages/k8s.html
- https://github.zhaw.ch/InIT-Operations/kubernetes-101
- https://kubernetes.io/docs/concepts/configuration/configmap/

**Comment by riesentoaster** [comment]
- [ ] Research `containerd`
  - [ ] Setup different parts as `containerd` images (CD)
- [ ] Research persistent storage
- [ ] Write k8s service `.yaml`s
- [ ] Setup CD

**Comment by riesentoaster** [comment]
[Docker vs containerd](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/).

> ## What does this change mean for developers, though? Do we still write Dockerfiles? Do we still build things with Docker?
> 
> This change addresses a different environment than most folks use to interact with Docker. The Docker installation you’re using in development is unrelated to the Docker runtime inside your Kubernetes cluster. It’s confusing, we understand. As a developer, Docker is still useful to you in all the ways it was before this change was announced. The image that Docker produces isn’t really a Docker-specific image—it’s an OCI ([Open Container Initiative](https://opencontainers.org/)) image. Any OCI-compliant image, regardless of the tool you use to build it, will look the same to Kubernetes. Both [containerd](https://containerd.io/) and [CRI-O](https://cri-o.io/) know how to pull those images and run them. This is why we have a standard for what containers should look like.

If I understand this correctly, we can build our entire CI/CD using docker and push the images to docker hub (or to a private repo, we'd need to discuss this). Kubernetes will pull these images and run them in containerd, regardless of how they were built.

**Comment by MrF3lix** [comment]
We could make use of the GitHub Packages in our Organization:
https://github.com/orgs/Agile-Waterfall-Inc/packages
