### ISSUE TITLE
Landing Page Content

### ISSUE THREAD

**Issue by nikipuk** [Agile-Waterfall-Inc/flooq#140]
Delegate the work of creating better text for different parts of the landing page.

This will not be merged in #126 

- Features
  - new/better Feature ideas
  - better text for existing Features

Anyone can create new Features with text.
If you think you have a better text for a feature, just add a new row with the same Feature name..
just add a comment with the same table 👍 

Make sure the text is between **90-130 characters**

| Feature | text |
|---|---|
| Visual Editor | Edit your Data Flows in an easy to use visual editor. Create new nodes to add new functionality to your Data Flow.  |
| Webhooks | Use the Data Flow url as your webhook. This allows you to access and use data provided in the webhook call. |
| Filter Data | Use the Filter Node to easily filter data. No more unnecessary large data structures for you! |
| Custom Scripts | Create a new Script Node to unlock the unlimited possibilities of java script in your Data Flow. |
| Scaling | With our robust backend infrastructure, we can ensure, that yor Data Flows will be handled as advertised. |
| Token Storage | We securely store your API Tokens. Saved Tokens can be used for different Data Flows and deleted at any time. |

here is what the feature cards look like:
![image](https://user-images.githubusercontent.com/36958001/168248648-96223180-16e4-46d2-831c-943721062aa5.png)

**Comment by MrF3lix** [comment]
@nikipuk branch should first be merged and then everyone can check the landing page on staging. Feedback and updated texts are in a separate PR.

**Comment by nikipuk** [comment]
> @nikipuk branch should first be merged and then everyone can check the landing page on staging. Feedback and updated texts are in a separate PR.

I think the texts can be created already, bit I'll add an image of the feature section.

**Comment by silvan-flum** [comment]
I like @riesentoaster's suggestion. Except that I'd change Token Storage a bit. Also, I think we should add Open Source as a feature. @nikipuk How important are the 90 - 130 characters?

## Overview-Text
Many web services provide automation APIs using webhooks. Use Flooq to connect incompatible endpoints and create complex automations! 

## Features
| Feature | Text |
|---|---|
| Visual Editor | Edit your data flows using a visual editor. No more configuring complicated text files! |
| API integrations | Connect your data flows to services without manually configuring request contents to satisfy the API format. |
| Transform Data | Include nodes in your data flow that filter, add, combine and transform data. |
| Custom Scripts | Create custom script nodes to unlock unlimited possibilities using JavaScript. |
| Token Storage | Securely store your API  access tokens and use them in any of your data flows. |
| Organisations | Collaborate with your colleagues when creating and maintaining data flows. Only available with certain plans. |
| Pay what you need | Start using Flooq for free. Upgrade to one of our custom plans once your requirements increase. |
| Open Source | Flooq is 100 % open source. This guarantees complete transparency and flexibility. |
