### ISSUE TITLE
Application name

### ISSUE THREAD

**Issue by Geissemanu** [Agile-Waterfall-Inc/flooq#17]
We need an application name, proposals:

- webHookers
- onlyHooks
- HookHub
- youHook
- goHookYourself
- hookUp
- Flook
- Fluctus

**Comment by nikipuk** [comment]
laminar.data

**Comment by MrF3lix** [comment]
- delego.io
- defluo.io
- fluo.io

**Comment by MrF3lix** [comment]
- Dorime
- Ameno

**Comment by MrF3lix** [comment]
Decided on: Flooq
