### ISSUE TITLE
Define DataFlow data structure

### ISSUE THREAD

**Issue by MrF3lix** [Agile-Waterfall-Inc/flooq#21]

**Comment by Geissemanu** [comment]
TODO:
Look at VM2, WebWorkers, docker

**Comment by riesentoaster** [comment]
### VM2
- Escape möglich, aber aufwändig
- Security by obscurity – Aber open source
- Entweder dumme Sandbox (`VM`) oder komplexere Systeme, die Imports erlauben (`nodeVM`), aber mühsamer sind betreffend timeouts.

### Docker
- Möglich
- Entweder pro User ein Pod/Docker/Container permanent laufen lassen oder on demand starten
- Startup-Time wohl niederer einstelliger Sekundenbetrag
	- Premium-Feature: Pod permanent laufen lassen

### Cloudflare Workers
- Wenn läuft: Sehr kurze response times
- Neuer Code-Push: 10-30s delay
- [API](https://api.cloudflare.com/#worker-script-upload-worker)
