### ISSUE TITLE
Execute a DataFlow

### ISSUE THREAD

**Issue by DuplosFidibuss** [Agile-Waterfall-Inc/flooq#49]
As a user I want to be able to execute a [Data Flow](https://github.com/Agile-Waterfall-Inc/flooq/blob/main/docs/glossary.md).

### Important

- This UC is dependent on list Data Flows
- This UC is dependent on the data structure for DataFlows

### Acceptance Criteria

- The executer offers a unique endpoint for each data flow.
- The executer can execute a data flow and return an http status code (e.g. 500 failed, 200 success).

**Comment by riesentoaster** [comment]
- [ ] Output-Node (`fetch`) – 
- [ ] Unique Endpoint per DataFlow – Valentin
- [ ] DataFlow to executable format – Manuel
- [ ] Execute such format – Lukas
