### ISSUE TITLE
Add javascript node

### ISSUE THREAD

**Issue by DuplosFidibuss** [Agile-Waterfall-Inc/flooq#50]
As a user I want to be able to add a node to a data flow that executes a custom javascript function that is defined by the user.

### Important

- This UC is dependent on execute a Data Flow

### Acceptance Criteria

- The editor should offer to add a new javascript node.
- The executer should be able to execute a javascript node.
  - At first [VM2](https://www.npmjs.com/package/vm2) is used to execute JavaScript. Once the authentication and token storage are implemented it will be replaced by a node that allows to add a [Cloudflare Worker](https://workers.cloudflare.com/) or something similar.

**Comment by MrF3lix** [comment]
Editor part is completed for now but I expect some minor changes once the executor part is implemented.
