### ISSUE TITLE
Add first data flow

### ISSUE THREAD

**Issue by MrF3lix** [Agile-Waterfall-Inc/flooq#77]
As a team member I want to receive a message in teams whenever a new issue is created.

### Acceptance criteria

- In teams a message should be posted in a sub channel of Agile Waterfall Inc. every time a new issue is created in GitHub.

**Comment by MrF3lix** [comment]
Check: https://editor-staging.flooq.io/flows/c87692b0-2648-4a49-bf99-57dcca94dde3

**Comment by nikipuk** [comment]
Awesome!
The flow is working for me, I tested it by creating #88
