### ISSUE TITLE
Save linearised graph

### ISSUE THREAD

**Issue by MrF3lix** [Agile-Waterfall-Inc/flooq#78]
As a user I want the fastest possible execution time. For this the data flow should be linearised at the first execution and then stored in the api.

### Acceptance Criteria

- The api should store a linearised version of the data flow
- The executor should linearise the data flow only after a change
- The executor should use the linearised version if it exists in the api

**Comment by Geissemanu** [comment]
- [ ] linearised dataFlow format
- [ ] Return linearised DataFlow to API
- [ ] save linearised DataFlow
- [ ] initialise linearisation after a change
- [ ] extract linerarisation into seperate Class / Pod
- [ ] return only linearised DataFlow to execute

**Comment by silvan-flum** [comment]
Change of DataFlow -> linearized Graph has to be deleted.
